# A pod with no securityContext specified.
# Without the webhook, it would run as user root (0). The webhook mutates it
# to run as the non-root user with uid 1234.
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-defaults
  labels:
    app: pod-with-defaults
  annotations: {
    aic.4paradigm.com/app: "true",
    aic.4paradigm.com/computeunit.busybox: "single-core"
  }
spec:
  restartPolicy: OnFailure
  containers:
    - name: busybox
      image: harbor.pineapple.com:32443/library/busybox:latest
      command: ["sh", "-c", "echo I am running as user $(id -u)"]
